language: node_js
install: npm install
script: npm test
node_js:
  - "4"
  - "5"
  - "6"
services:
  - mysql
  - postgresql
env:
  - DB=mysql
  - DB=postgresql
before_install:
  - if [ $DB == "mysql" ]; then mysql -e 'create database tastypie'; fi
  - if [ $DB == "mysql" ]; then export database__connection__user=travis; fi
  - if [ $DB == "pg" ]; then psql -c 'create database tastypie;' -U postgres; fi
  - if [ $DB == "pg" ]; then export database__connection__user=postgres; fi
  - if [ $DB == "pg" ]; then export psql -l; fi
before_script:
  - printenv | sort
  - node scripts/bootstrap
