language: node_js
install: npm install
script: npm test
node_js:
  - "4"
  - "5"
  - "6"
services:
  - mysql
  - postgresql
env:
  - DB=mysql
  - DB=postgresql
before_install:
  - if [ $DB == "mysql" ]; then mysql -e 'create database tastypie'; fi
  - if [ $DB == "pg" ]; then psql -c 'create database tastypie;' -U postgres; fi
before_script:
  - node script/boostrap
